create index profiles_email_idx on public.profiles (email);
create index family_members_user_idx on public.family_members (user_id);
create index family_members_family_idx on public.family_members (family_id);
create index children_family_idx on public.children (family_id);
create index custody_events_family_start_idx on public.custody_events (family_id, start_at);
create index custody_events_child_start_idx on public.custody_events (child_id, start_at);
create index change_requests_family_idx on public.change_requests (family_id, status);
create index handover_logs_family_created_idx on public.handover_logs (family_id, created_at desc);
create index contacts_family_child_idx on public.contacts (family_id, child_id);
create index documents_family_category_idx on public.documents (family_id, category);
create index message_threads_family_idx on public.message_threads (family_id, updated_at desc);
create index messages_thread_created_idx on public.messages (thread_id, created_at);
create index expenses_family_status_idx on public.expenses (family_id, status);
create index decision_requests_family_status_idx on public.decision_requests (family_id, status);
create index disputes_family_status_idx on public.disputes (family_id, status);
create index personal_journal_user_idx on public.personal_journal_entries (user_id, created_at desc);
create index reports_family_generated_idx on public.reports (family_id, generated_at desc);
create index audit_logs_family_created_idx on public.audit_logs (family_id, created_at desc);
create index subscriptions_user_status_idx on public.subscriptions (user_id, status);
create index external_notifications_token_idx on public.external_notifications (token);
